name: Automatic build

on: [push]

jobs:
  Linux:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libxss1 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 qt5-default libqt5gui5 libqt5webengine5 libqt5webenginecore5 libqt5webenginewidgets5 libqt5printsupport5 libqt5quickwidgets5 qml-module-qtquick-controls libqt5x11extras5 binutils cmake pkg-config qtbase5-dev qtwebengine5-dev libqt5x11extras5-dev  qtbase5-private-dev libssl-dev libxss-dev libxmu-dev
    - name: Configure
      run: qmake .
    - name: Build
      run: make -j2

  macOS:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        brew install qt
        echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile
        brew install xz
        brew install git
    - name: Configure
      run: |
        export PATH="/usr/local/opt/qt/bin:/usr/local/opt/git/bin:$PATH"
        ls /usr/local/opt/qt/bin
        qmake .
    - name: Build
      run: make -j2

  Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Tools
      shell: bash
      run: |
        mkdir -p /d/a/MediaWriter/Qt
        cd /d/a/MediaWriter/Qt
        # I seriously don't know how else to do this, I tried every combination of arguments to all tools I found and it still failed
        # I don't feel particularly inclined to using the official installer as well, especially since they introduced the need to log in to use it
        curl -L https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_mingw/qt.tools.win32_mingw730/7.3.0-1-201903151311i686-7.3.0-release-posix-dwarf-rt_v5-rev0.7z --output compiler.7z
        7z ea compiler.7z
        rm compiler.7z
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch: win32_mingw73
    - name: Build
      shell: bash
      run: |
        export PATH=$(echo "$PATH" | sed -e 's/:\/c\/ProgramData\/Chocolatey\/bin//' | sed -e 's/:\/c\/Strawberry\/c\/bin//')
        export PATH="$Qt5_Dir/../../Tools:$PATH"
        mkdir build
        cd build
        "$Qt5_Dir/bin/qmake" ..
        mingw32-make -j2 VERBOSE=1

